# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d1528513fa726a1a8ec66f664e071deb07325554e6ed0c933e3a507648293e047cd07dc00009fb1db1772792cb68682b33f2890c7da949ab4c5ac1e57eeb483

test:
  secret_key_base: f1465bdc0026fefba75ad6e433093cdee409f819a869b8ff6ed895d6c67ee4d18bcd1e1d688809eff734911e94f405a19448efe511a871bea9d380c7e13aec48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
